name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create zip file
        run: |
          zip -r konnected_legacy.zip custom_components/

      - name: Delete old release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete v1.0.0 --yes || true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          name: v1.0.0
          draft: false
          prerelease: false
          files: |
            konnected_legacy.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
