name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create zip file
        run: |
          zip -r konnected_legacy.zip custom_components/

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.0
          name: v1.0.0
          artifacts: konnected_legacy.zip
          artifactContentType: application/zip
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
